### ISSUE TITLE
[$60] Database migrations

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-notifications#16]
We need to create migrations for the database.
Initial db state should be the one before we added version column to notifications table, and the first migration should be adding the version column. We'll use this when releasing the next version to prod

**Comment by maxceem** [comment]
Is that ok to use something like [npm db-migrate](https://www.npmjs.com/package/db-migrate), to manage migrations?

**Comment by gondzo** [comment]
I'd preferr sequelize cli, same as tc-message-service
https://github.com/topcoder-platform/tc-message-service

**Comment by gondzo** [comment]
No need folr migrations ATM
