### ISSUE TITLE
Filter notification specific to platform.

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-notifications#171]
Provide support in API call to filter platform specific notification

**Comment by sachin-maheshwari** [comment]
Fixed and Released in PR - https://github.com/topcoder-platform/tc-notifications/pull/168

**Comment by lakshmiathreya** [comment]
@sachin-maheshwari i am unable to close the Issue. Pl add me to Repo.

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya  done
