### ISSUE TITLE
Add country filter support for broadcast 

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-notifications#193]
Currently we can filter on groups, skills and tracks.

**Comment by SathyaJayabal** [comment]
verified on dev and prod
![2](https://user-images.githubusercontent.com/58783823/81035318-14a97d00-8eb8-11ea-9583-b49a43154d0e.png)
<img width="1427" alt="Screenshot 2020-04-30 at 10 34 37 AM" src="https://user-images.githubusercontent.com/58783823/81035322-18d59a80-8eb8-11ea-84df-7ca0dad3ab79.png">

**Comment by lakshmiathreya** [comment]
@drasticdpk pls update findings for Connect email template changes and post them here ... will close Issue once done ...

**Comment by drasticdpk** [comment]
As discussed with Dev Team, for now there is no needed verification from connect app. So closing this issue. cc @lakshmiathreya @vikasrohit
