### ISSUE TITLE
Support multiple mentions - right now it only sends mention event for first mention in the post

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-notifications#37]
@gondzo can you please take care of it?

**Comment by maxceem** [comment]
@gondzo 
When I create a post https://connect.topcoder-dev.com/projects/2000 and mention some people. I get only `notifications.action.email.connect.project.topic.created` event in my locally deployed `tc-notifications` service. It looks like mention events are not being sent to the KAFKA at all.

**Comment by vikasrohit** [comment]
@maxceem We don't send mention event from message service rather tc-notifications actually parses the content of the new topic/post in case of `notifications.action.email.connect.project.topic.created` or `notifications.action.email.connect.project.post.created` events and internally changes the event type when sending email to the team members. So, yes, it does not send any event to the bus right now.
We can move that logic to tc-message-service, if that makes more sense.

**Comment by maxceem** [comment]
@vikasrohit thank you. I've missed that moment. I think it's totally fine to keep like it's done now. Will make sure mentions are processed correctly.
