### ISSUE TITLE
Refactor logic of email notification handling

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-notifications#38]
Extract logic of email notification handling to a separate handler instead of directly coding it in app.js.

**Comment by maxceem** [comment]
1. Regarding source code, notifications are being sent by email only after they are saved in the DB.

```js
models.Notification.create({
 ...
 })
 .then(() => {
   // send email
 })
```
I don't see any reasons why these actions couldn't be done in parrallel. Even if saving notification to the DB fails, looks like there are no reasons to stop sending email.

@gondzo  Do you know any reasons I'm missing not to make it parrallel?

**Comment by vikasrohit** [comment]
Yes @maxceem, you are right. That is what the purpose of this issue/task is. However, right now while saving notifications in database, code validates different events and might alter the event type e.g. in case of a user's handle in mentioned in a post, it changes the event type to MENTIONED_IN_POST from POST_CREATED and the email sending logic is using that updated event type.
What we are thinking is to have post handlers (like we have handlers for all events) which handles the notifications saved in database and do additional things like email, slack etc. However, we are still open for any other good approach which removes the clutter from app.js and makes the code more maitainable.

**Comment by vikasrohit** [comment]
Excellent question @maxceem In fact that is my intention in getting this refactoring done. Ideally this code in app.js should belong to the `connectNotificationServer`.  Right now I am not sure how we are going to separate the specific implementation of notification servers, but I think we can definitely utilize https://github.com/topcoder-platform/tc-connect-notifications to host the connectNotificationServer. @gondzo what do you think?

**Comment by maxceem** [comment]
@vikasrohit great, so far I've moved all the code related to connect from `/src` to `/connect`.
