### ISSUE TITLE
Handle user mention in post update event

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-notifications#39]
Handle user mention in post update event

@vikasrohit I think we're handling updates correctly in tc-notifications

https://github.com/topcoder-platform/tc-notifications/blob/d8b60beb4b97b44acb2fae9fff202c4a1f9a0747/connect/events-config.js#L123

**Comment by vikasrohit** [comment]
Yes, I thought we are not. Actually mention was not working because of mismatch regex of markdown. It assumed post to be in cooked format always while now we have only raw format which is in markdown format.
Closing the issue, we just need to support multiple mentions.
